baseURL = 'https://he2121.github.io/xiaohe-blog/'
languageCode = 'zh-cn'
defaultContentLanguage = 'zh'
title = '小贺的博客'
publishDir = 'docs'
theme = 'mini'

googleAnalytics = 'G-FY1WNXTY3L'
disqusShortname = 'heganghuan-blog'

[social]
github = "https://github.com/he2121/"

[params]
author = '小贺'
bio = 'Golang 工程师'
description = "小贺的博客"
enableGoogleAnalytics = true
enableComments = false
hiddenPostSummaryInHomePage = true
showPowerBy = false

[[params.links]]
name = "算法"
path = "/xiaohe-blog/algorithm"
[[params.links]]
name = "杂谈"
path = "/xiaohe-blog/mixed"
[[params.links]]
name = "读书"
path = "/xiaohe-blog/reading"